[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/boiling_viz"]

[project]
name = "boiling_viz"
version = "0.1.0"
description = "Utilities for making images and videos"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "matplotlib",
    "h5py",
    "manim",
    "imageio",
    "pytest",
    "seaborn",
    "ruff"
]

[project.urls]
"Homepage" = "https://github.com/therml-ai/boiling-viz"